---
# tasks setup for ansible-role-logrotate

- name: Ensure logrotate.d directory is present
  file:
    path: "{{ logrotate_include_file }}"
    owner: "{{ logrotate_config_owner }}"
    group: "{{ logrotate_config_group }}"
    state: directory

- name: Configure logrotate
  template:
    src: "logrotate.j2"
    dest: "{{ logrotate_configfile }}"
    owner: "{{ logrotate_config_owner }}"
    group: "{{ logrotate_config_group }}"
    mode: 0600

- name: Create logrotate application configuration files
  template:
    src: application.j2
    dest: "{{ logrotate_include_file }}/{{ item.name }}"
    owner: "{{ logrotate_config_owner }}"
    group: "{{ logrotate_config_group }}"
    mode: 0600
  with_items:
    - '{{ logrotate_applications }}'
